# Generated by Django 5.0.1 on 2026-02-17 01:56

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NegativeLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the negative link', primary_key=True, serialize=False)),
                ('url', models.TextField(help_text='URL of the negative content', validators=[django.core.validators.URLValidator()])),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('youtube', 'YouTube'), ('reddit', 'Reddit'), ('other', 'Other')], help_text='Platform where the content is hosted', max_length=20)),
                ('type', models.CharField(choices=[('post', 'Post'), ('comment', 'Comment'), ('video', 'Video'), ('article', 'Article')], help_text='Type of content', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('removed', 'Removed'), ('in_work', 'In Work'), ('pending', 'Pending')], default='pending', help_text='Current status of the link', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True, help_text='When the link was first detected')),
                ('removed_at', models.DateTimeField(blank=True, help_text='When the link was removed', null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Priority level for handling this link', max_length=10)),
                ('manager', models.CharField(blank=True, help_text='Manager assigned to handle this link', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this link', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
            ],
            options={
                'verbose_name': 'Negative Link',
                'verbose_name_plural': 'Negative Links',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['platform', 'status'], name='links_negat_platfor_9f0ed2_idx'), models.Index(fields=['status', 'priority'], name='links_negat_status_126fcb_idx'), models.Index(fields=['manager'], name='links_negat_manager_77ed11_idx'), models.Index(fields=['detected_at'], name='links_negat_detecte_ff5805_idx')],
            },
        ),
    ]
