# Generated by Django 5.0.1 on 2026-02-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_add_account_type'),
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negativelink',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('removed', 'Removed'), ('in_work', 'In Work'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the link', max_length=20),
        ),
        migrations.AddIndex(
            model_name='negativelink',
            index=models.Index(fields=['manager'], name='links_negat_manager_c69cc3_idx'),
        ),
    ]
